### PR TITLE
Add redirects

### PR DESCRIPTION
**Pull request by aman207**
Add 10 new redirects and tweaked a couple more.

Tweaks:
Amazon: include ".ca" and ".com"
Bestbuy: remove tracking parameters that are part of the URL
sjv.io: match all subdomains

New redirect examples:

pjtra.com
pntra.com
pntrs.com
pjatr.com
pntrac.com
These domains seem to be rotated through. Here are a few links which I've seen them appear:
https://forums.redflagdeals.com/sporting-life-under-armor-surge-3-running-shoe-men-women-junior-kids-babies-39-98-less-2673463/
https://forums.redflagdeals.com/canon-ca-rbc-clients-75-statement-credit-500-spend-get-250-creditfortravel-money-500-spend-until-feb-29-2672925/
https://forums.redflagdeals.com/golf-town-golf-town-womens-2021-m4-6-pw-sw-iron-set-graphite-shafts-524-99-2666699/

shareasale.com
https://forums.redflagdeals.com/fastestvpn-fastestvpn-27-usd-lifetime-plan-15-multi-logins-2666156/

mkr3.net
https://forums.redflagdeals.com/eddie-bauer-stowaway-packable-sling-3-0-30-50-off-2671096/#p38643194

fintelconnect.com
https://forums.redflagdeals.com/tangerine-earnmore-new-client-promo-earn-up-400-20-cash-back-6-00-savings-rate-5-months-2636126/#p37970401

c2ukkg.net
https://forums.redflagdeals.com/simons-cloudmonster-sneakers-men-25-off-149-95-use-10-off-comes-down-139-95-2671888/#p38655962

dodxnr.net
https://forums.redflagdeals.com/gap-extra-50-off-sale-20-off-code-10-cash-back-2671539/#p38647526

### CODE REVIEW

**Comment by davegallant** [comment]
Thanks. Would you be able to update your branch with the latest from main? I think I've fixed the 'Generate Tampermonkey' workflow.

**Comment by aman207** [comment]
> Thanks. Would you be able to update your branch with the latest from main? I think I've fixed the 'Generate Tampermonkey' workflow.

Done. Looks like a different error this time at least!

**Comment by davegallant** [comment]
> > Thanks. Would you be able to update your branch with the latest from main? I think I've fixed the 'Generate Tampermonkey' workflow.
> 
> Done. Looks like a different error this time at least!

Ah, I think it might be due to [this](https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#use-in-forks-from-public-repositories).
> Ensure your contributors enable "Allow edits by maintainers" when opening a pull request

I've added it to main branch as well.

**Comment by aman207** [comment]
> > > Thanks. Would you be able to update your branch with the latest from main? I think I've fixed the 'Generate Tampermonkey' workflow.
> > 
> > 
> > Done. Looks like a different error this time at least!
> 
> Ah, I think it might be due to [this](https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#use-in-forks-from-public-repositories).
> 
> > Ensure your contributors enable "Allow edits by maintainers" when opening a pull request

Ah OK, good to know

**Pull request merged**
